apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-radar-redis
  namespace: {{ .Release.Namespace }}
  labels:
    app: stock-radar-redis
    app.kubernetes.io/part-of: stock-radar-system
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: stock-radar-redis
  template:
    metadata:
      labels:
        app: stock-radar-redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["--save", "", "--appendonly", "no"]
          ports:
            - name: redis
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
