apiVersion: v1
kind: Endpoints
metadata:
  name: stock-radar-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stock-radar.labels" . | nindent 4 }}
subsets:
  - addresses:
      - ip: 192.168.1.77
    ports:
      - port: {{ .Values.env.port }}
        name: pg
