apiVersion: v1
kind: Service
metadata:
  name: stock-radar-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stock-radar.labels" . | nindent 4 }}
spec:
  ports:
    - name: pg
      port: {{ .Values.env.port }}
      targetPort: pg
