apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.global.sharedServiceAccountName }}-binding
  labels:
    app.kubernetes.io/part-of: stock-radar-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.global.sharedServiceAccountName }}-clusterrole
subjects:
  - kind: ServiceAccount
    name: {{ .Values.global.sharedServiceAccountName }}
    namespace: {{ .Release.Namespace }}
