apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.sharedServiceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: stock-radar-system
automountServiceAccountToken: true
