apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-radar-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app: stock-radar-frontend
    app.kubernetes.io/part-of: stock-radar-system
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: stock-radar-frontend
  template:
    metadata:
      labels:
        app: stock-radar-frontend
    spec:
      serviceAccountName: {{ .Values.global.sharedServiceAccountName }}
      containers:
        - name: frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
