"""initial schema in stock_radar

Revision ID: eccb39e7875c
Revises: 
Create Date: 2026-03-15 20:08:01.387574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eccb39e7875c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('signal_type', sa.Enum('BREAKOUT', 'FALSE_BREAKOUT', name='signaltype'), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('liquidity_imbalance', sa.Float(), nullable=True),
    sa.Column('spread_compression', sa.Float(), nullable=True),
    sa.Column('bid_stacking', sa.Float(), nullable=True),
    sa.Column('volume_acceleration', sa.Float(), nullable=True),
    sa.Column('order_aggression', sa.Float(), nullable=True),
    sa.Column('acted_on', sa.Boolean(), nullable=False),
    sa.Column('outcome_pnl', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='stock_radar'
    )
    op.create_index(op.f('ix_stock_radar_signals_ticker'), 'signals', ['ticker'], unique=False, schema='stock_radar')
    op.create_table('symbols',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('avg_volume', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='stock_radar'
    )
    op.create_index(op.f('ix_stock_radar_symbols_ticker'), 'symbols', ['ticker'], unique=True, schema='stock_radar')
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='tradeside'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'FILLED', 'PARTIAL', 'CANCELLED', 'CLOSED', name='tradestatus'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('stop_loss_price', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('signal_score', sa.Float(), nullable=True),
    sa.Column('entry_time', sa.DateTime(), nullable=True),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='stock_radar'
    )
    op.create_index(op.f('ix_stock_radar_trades_ticker'), 'trades', ['ticker'], unique=False, schema='stock_radar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_radar_trades_ticker'), table_name='trades', schema='stock_radar')
    op.drop_table('trades', schema='stock_radar')
    op.drop_index(op.f('ix_stock_radar_symbols_ticker'), table_name='symbols', schema='stock_radar')
    op.drop_table('symbols', schema='stock_radar')
    op.drop_index(op.f('ix_stock_radar_signals_ticker'), table_name='signals', schema='stock_radar')
    op.drop_table('signals', schema='stock_radar')
    # ### end Alembic commands ###
