apiVersion: v1
kind: Service
metadata:
  name: stock-radar-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: stock-radar-api
    app.kubernetes.io/part-of: stock-radar-system
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: stock-radar-api
