apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-radar-grafana
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-radar-grafana
  template:
    metadata:
      labels:
        app: stock-radar-grafana
    spec:
      containers:
        - name: grafana
          image: {{ .Values.grafana.image }}
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: {{ .Values.grafana.adminPassword | quote }}
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: dashboard-provider
              mountPath: /etc/grafana/provisioning/dashboards
            - name: dashboards
              mountPath: /var/lib/grafana/dashboards
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
      volumes:
        - name: datasources
          configMap:
            name: stock-radar-grafana-datasources
        - name: dashboard-provider
          configMap:
            name: stock-radar-grafana-dashboards-provider
        - name: dashboards
          configMap:
            name: stock-radar-grafana-dashboard
